# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme
shell = "zsh"

#
# defer
#
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

#
# apperance
#
[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

#
# completion
#
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.base16]
github = "chriskempson/base16-shell"

#
# utility
#
[plugins.zpm-zsh-ls]
github = "zpm-zsh/ls"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.zsh-up-dir]
github = "sgpthomas/zsh-up-dir"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"

[plugins.prezto-spectrum]
remote = "https://raw.githubusercontent.com/sorin-ionescu/prezto/refs/heads/master/modules/spectrum/init.zsh"

#
# dev tools
#
[plugins.zsh-git-fzf]
github = "alexiszamanidis/zsh-git-fzf"

[plugins.zsh-terraform]
github = "ptavares/zsh-terraform"

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"

[plugins.zsh-saml2aws]
github = "onyxraven/zsh-saml2aws"

[plugins.oh-my-kustomize]
github = "ralgozino/oh-my-kustomize"

# [plugins.kubectl_fzf]
# remote = "https://raw.githubusercontent.com/bonnefoa/kubectl-fzf/refs/heads/main/shell/kubectl_fzf.plugin.zsh"
# apply = ["PATH", "source"]

# [plugins.autojump]
# github = "wting/autojump"
# dir = "bin"
# apply = ["PATH", "source"]


#[plugins.prezto-spectrum]
#remote = "https://github.com/sorin-ionescu/prezto/blob/master/modules/spectrum/init.zsh"
# For example:
#
