# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme
shell = "zsh"

#
# defer
#
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

#
# apperance
#
[plugins.prezto-spectrum]
remote = "https://raw.githubusercontent.com/sorin-ionescu/prezto/refs/heads/master/modules/spectrum/init.zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

#
# completion
#
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

#
# utility
#
[plugins.zpm-zsh-ls]
github = "zpm-zsh/ls"

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["defer"]

[plugins.zsh-up-dir]
github = "sgpthomas/zsh-up-dir"
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"
apply = ["defer"]


#
# dev tools
#
[plugins.zsh-git-fzf]
github = "alexiszamanidis/zsh-git-fzf"
apply = ["defer"]

[plugins.zsh-terraform]
github = "ptavares/zsh-terraform"
apply = ["defer"]

[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"
apply = ["defer"]

[plugins.zsh-saml2aws]
github = "onyxraven/zsh-saml2aws"
apply = ["defer"]

[plugins.oh-my-kustomize]
github = "ralgozino/oh-my-kustomize"
apply = ["defer"]
